export const userActionTypes = {
    REGISTRATION_SUCCESS:'REGISTRATION_SUCCESS',
    REGISTRATION_FAIL:'REGISTRATION_FAIL',
    USER_LOADED_SUCCESS:'USER_LOADED_SUCCESS',
    USER_LOADED_FAILED:'USER_LOADED_FAILED',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL'
}